name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9:00 AM

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Run tests against Apple's Combine
        run: make test-compatibility
        