name: Compatibility tests 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compatibility_tests_macos:
    name: Execute compatibility tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            xcode-version: "14.2"   # Swift 5.7.2
          - os: macos-13
            xcode-version: "15.1"   # Swift 5.9.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Run tests against Apple's Combine
        run: make test-compatibility
        