name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  carton_wasmer_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.7", "5.8", "5.9"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/swiftwasm-action@v${{ matrix.swift_version }}