name: Wasm 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Matrics is not supported
  # See https://github.com/swiftwasm/swiftwasm-action/issues/3
  carton_wasmer_test_5_7:
    name: "Execute tests on Wasm (Swift 5.7)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/swiftwasm-action@v5.7
  carton_wasmer_test_5_8:
    name: "Execute tests on Wasm (Swift 5.8)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.8
  carton_wasmer_test_5_9:
    name: "Execute tests on Wasm (Swift 5.9)"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.9